version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111

  ewm-service:
    build: main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111

