drop table if exists users cascade;
drop table if exists categories cascade;
drop table if exists events cascade;
drop table if exists requests cascade;
drop table if exists compilations cascade;
drop table if exists compilations_events cascade;

create table if not exists users (
    id bigint generated by default as identity primary key not null,
    name varchar(255) not null,
    email varchar(255) not null unique
);

create table if not exists categories (
    id bigint generated by default as identity primary key not null,
    name varchar(50) not null
);

create table if not exists events (
    id bigint generated by default as identity primary key not null,
    annotation text,
    category_id bigint references categories (id) on delete cascade,
    confirmed_requests bigint,
    created_on timestamp without time zone,
    description text,
    event_date timestamp without time zone,
    initiator_id bigint references users (id) on delete cascade,
    lat float,
    lon float,
    paid boolean,
    participant_limit bigint,
    published_on timestamp without time zone,
    request_moderation boolean,
    state varchar,
    title varchar,
    views bigint
);


create table if not exists requests (
    id bigint generated by default as identity primary key not null,
    created timestamp without time zone,
    event_id bigint not null references events (id) on delete cascade,
    requester_id bigint not null references users (id) on delete cascade,
    status varchar not null
);


create table if not exists compilations (
    id bigint generated by default as identity primary key not null,
    pinned boolean,
    title varchar(50) unique
);

create table if not exists compilations_events (
    event_id bigint references events (id),
    compilation_id bigint references compilations (id)
);